### ISSUE TITLE
Do you have an executable build for Linux (like AppImage)?

### ISSUE THREAD

**Issue by xydan83** [oniksan/weprex#1]
Hi!
I see that you don't have an executable build for Linux like Debian (Ubuntu) in AppImage.
I wrote a couple of script files to build this package on Linux, I can share them if you want.

**Comment by oniksan** [comment]
Hi!
You can attach your scripts and make a PR.

**Comment by xydan83** [comment]
> Hi! You can attach your scripts and make a PR.

Done. Check plz.
https://github.com/oniksan/weprex/pull/2
